import abc
import asyncio
from typing import Any, Dict

class BaseAgent(abc.ABC):
    """Abstract base class for all specialized agents in the system."""

    @abc.abstractmethod
    async def run(self, inputs: Dict[str, Any], queue: asyncio.Queue[Any]) -> Dict[str, Any]:
        """
        Executes the agent logic.
        
        Args:
            inputs: Dict containing task inputs and dependencies outputs.
            queue: The queue used to stream OutputChunk updates to the client.
            
        Returns:
            Dict containing the outputs generated by the agent.
        """
        pass
